{
 "title": "Robert",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_idm_feedin\nFROM solar_idm_feedin\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_kostal_consumption_total\nFROM solar_kostal_consumption_total\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_kostal_generation_total\nFROM solar_kostal_generation_total\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_kostal_inverter\nFROM solar_kostal_inverter\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_kostal_powertogrid\nFROM solar_kostal_powertogrid\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_kostal_surplus\nFROM solar_kostal_surplus\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_soyosource\nFROM solar_soyosource\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Batterie und Ladegeraet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_battery_chargestatus\nFROM solar_battery_chargestatus\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_kostal_batteryflag\nFROM solar_kostal_batteryflag\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as solar_kostal_batterypercent\nFROM solar_kostal_batterypercent\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value as technical_room_temperature\nFROM technical_room_temperature\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}