version: '3'
services:
    vsc-server:
        build: vsc
        hostname: code-server-solar-manager
        volumes:
            - $HOME/.config:/home/coder/.config
            - $HOME/.gitconfig:/home/coder/.gitconfig
            - $PWD:/home/coder/project
        #devices:
            #- "/dev/ttyUSB0:/dev/ttyUSB0"
        environment:
            - DOCKER_USER=$USER
        user: "${EXAMPLE_UID}:${EXAMPLE_GID}"
        expose:
            - 8080
        ports:
            - 8080:8080


