CREATE TABLE solar_byd_soc ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_soc', 'time');
ALTER TABLE solar_byd_soc SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_soc', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_soc', INTERVAL '7 days');
CREATE TABLE solar_byd_maxvolt ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_maxvolt', 'time');
ALTER TABLE solar_byd_maxvolt SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_maxvolt', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_maxvolt', INTERVAL '7 days');
CREATE TABLE solar_byd_minvolt ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_minvolt', 'time');
ALTER TABLE solar_byd_minvolt SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_minvolt', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_minvolt', INTERVAL '7 days');
CREATE TABLE solar_byd_soh ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_soh', 'time');
ALTER TABLE solar_byd_soh SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_soh', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_soh', INTERVAL '7 days');
CREATE TABLE solar_byd_maxtemp ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_maxtemp', 'time');
ALTER TABLE solar_byd_maxtemp SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_maxtemp', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_maxtemp', INTERVAL '7 days');
CREATE TABLE solar_byd_mintemp ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_mintemp', 'time');
ALTER TABLE solar_byd_mintemp SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_mintemp', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_mintemp', INTERVAL '7 days');
CREATE TABLE solar_byd_battemp ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_battemp', 'time');
ALTER TABLE solar_byd_battemp SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_battemp', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_battemp', INTERVAL '7 days');
CREATE TABLE solar_byd_error ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_error', 'time');
ALTER TABLE solar_byd_error SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_error', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_error', INTERVAL '7 days');
CREATE TABLE solar_byd_power ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_power', 'time');
ALTER TABLE solar_byd_power SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_power', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_power', INTERVAL '7 days');
CREATE TABLE solar_byd_diffvolt ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_byd_diffvolt', 'time');
ALTER TABLE solar_byd_diffvolt SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_byd_diffvolt', INTERVAL '1 days');
SELECT add_retention_policy('solar_byd_diffvolt', INTERVAL '7 days');
