CREATE TABLE solar_battery_charger_yesterday ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_battery_charger_yesterday', 'time');
ALTER TABLE solar_battery_charger_yesterday SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_battery_charger_yesterday', INTERVAL '1 days');
SELECT add_retention_policy('solar_battery_charger_yesterday', INTERVAL '7 days');
CREATE TABLE solar_battery_charger_today ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_battery_charger_today', 'time');
ALTER TABLE solar_battery_charger_today SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_battery_charger_today', INTERVAL '1 days');
SELECT add_retention_policy('solar_battery_charger_today', INTERVAL '7 days');