CREATE TABLE solar_kostal_dailyyield ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_kostal_dailyyield', 'time');
ALTER TABLE solar_kostal_dailyyield SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_kostal_dailyyield', INTERVAL '1 days');
SELECT add_retention_policy('solar_kostal_dailyyield', INTERVAL '7 days');
CREATE TABLE solar_kostal_homeconsumption ( "time" timestamptz NOT NULL , "value" double precision );
SELECT create_hypertable('solar_kostal_homeconsumption', 'time');
ALTER TABLE solar_kostal_homeconsumption SET ( timescaledb.compress, timescaledb.compress_segmentby = 'time' );
SELECT add_compression_policy('solar_kostal_homeconsumption', INTERVAL '1 days');
SELECT add_retention_policy('solar_kostal_homeconsumption', INTERVAL '7 days');